stages:
  - build
  - deploy

esp32s2_wroom_at:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp-env-v5.0:2
  tags:
    - build

  variables:
    IDF_PATH: "$CI_PROJECT_DIR/esp-idf"
    GIT_STRATEGY: clone

  artifacts:
    paths:
      - build/*.bin
      - build/*.elf
      - build/*.map
      - build/bootloader/*.bin
      - build/partition_table/*.bin
      - build/customized_partitions/*.bin
      - build/flasher_args.json
      - build/download.config
      - build/factory/*
    expire_in: 6 mos

  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    # - git submodule update --init --recursive

  script:
    - cd main
    - rm -f at_config.h
    - echo -e "#ifndef __AT_CONFIG_H__" >> at_config.h
    - echo -e "#define __AT_CONFIG_H__" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_WROOM \"$AT_OTA_TOKEN_ESP32S2_WROOM\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_WROOM \"$AT_OTA_TOKEN_ESP32S2_WROOM\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_WROVER \"$AT_OTA_TOKEN_ESP32S2_WROVER\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_WROVER \"$AT_OTA_TOKEN_ESP32S2_WROVER\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_SOLO \"$AT_OTA_TOKEN_ESP32S2_SOLO\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_SOLO \"$AT_OTA_TOKEN_ESP32S2_SOLO\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_MINI \"$AT_OTA_TOKEN_ESP32S2_MINI\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_MINI \"$AT_OTA_TOKEN_ESP32S2_MINI\"" >> at_config.h
    - echo -e "#endif" >> at_config.h
    - cd -
    # replace submodule esp-idf to internal repository to speedup cloning
    - commit_str=$(awk '/commit:/{print $0}' module_config/module_esp32s2_default/IDF_VERSION)
    - branch_str=$(awk '/branch:/{print $0}' module_config/module_esp32s2_default/IDF_VERSION)
    - git clone -b ${branch_str#*branch:} ${GITLAB_SSH_SERVER}/idf/esp-idf.git
    - cd esp-idf
    - git checkout ${commit_str#*commit:}
    # (the same regular expressions are used to set these are used in 'only:' sections below
    - source ./tools/ci/configure_ci_environment.sh
    - tools/idf_tools.py install-python-env
    - tools/idf_tools.py install
    - source export.sh
    # fetch the submodules (& if necessary re-fetch repo) from gitlab
    - time ./tools/ci/get-full-sources.sh
    - git submodule update --init
    - cd -

    - export ESP_AT_PROJECT_PLATFORM=PLATFORM_ESP32S2
    - export ESP_AT_MODULE_NAME=WROOM
    - export ESP_AT_PROJECT_PATH=$(pwd)
    - pip install -r requirements.txt
    - ./esp-idf/tools/idf.py -DIDF_TARGET=esp32s2 build
    - cp build/flash_project_args build/download.config
    # - make print_flash_cmd | tail -n 1 > build/download.config
    # - make factory_bin

esp32s2_wrover_at:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp-env-v5.0:2
  tags:
    - build

  variables:
    IDF_PATH: "$CI_PROJECT_DIR/esp-idf"
    GIT_STRATEGY: clone

  artifacts:
    paths:
      - build/*.bin
      - build/*.elf
      - build/*.map
      - build/bootloader/*.bin
      - build/partition_table/*.bin
      - build/customized_partitions/*.bin
      - build/flasher_args.json
      - build/download.config
      - build/factory/*
    expire_in: 6 mos

  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    # - git submodule update --init --recursive

  script:
    - cd main
    - rm -f at_config.h
    - echo -e "#ifndef __AT_CONFIG_H__" >> at_config.h
    - echo -e "#define __AT_CONFIG_H__" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_WROOM \"$AT_OTA_TOKEN_ESP32S2_WROOM\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_WROOM \"$AT_OTA_TOKEN_ESP32S2_WROOM\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_WROVER \"$AT_OTA_TOKEN_ESP32S2_WROVER\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_WROVER \"$AT_OTA_TOKEN_ESP32S2_WROVER\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_SOLO \"$AT_OTA_TOKEN_ESP32S2_SOLO\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_SOLO \"$AT_OTA_TOKEN_ESP32S2_SOLO\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_MINI \"$AT_OTA_TOKEN_ESP32S2_MINI\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_MINI \"$AT_OTA_TOKEN_ESP32S2_MINI\"" >> at_config.h
    - echo -e "#endif" >> at_config.h
    - cd -
    # replace submodule esp-idf to internal repository to speedup cloning
    - commit_str=$(awk '/commit:/{print $0}' module_config/module_esp32s2_default/IDF_VERSION)
    - branch_str=$(awk '/branch:/{print $0}' module_config/module_esp32s2_default/IDF_VERSION)
    - git clone -b ${branch_str#*branch:} ${GITLAB_SSH_SERVER}/idf/esp-idf.git
    - cd esp-idf
    - git checkout ${commit_str#*commit:}
    # (the same regular expressions are used to set these are used in 'only:' sections below
    - source ./tools/ci/configure_ci_environment.sh
    - tools/idf_tools.py install-python-env
    - tools/idf_tools.py install
    - source export.sh
    # fetch the submodules (& if necessary re-fetch repo) from gitlab
    - time ./tools/ci/get-full-sources.sh
    - git submodule update --init
    - cd -

    - export ESP_AT_PROJECT_PLATFORM=PLATFORM_ESP32S2
    - export ESP_AT_MODULE_NAME=WROVER
    - export ESP_AT_PROJECT_PATH=$(pwd)
    - pip install -r requirements.txt
    - ./esp-idf/tools/idf.py -DIDF_TARGET=esp32s2 build
    - cp build/flash_project_args build/download.config

esp32s2_solo_at:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp-env-v5.0:2
  tags:
    - build

  variables:
    IDF_PATH: "$CI_PROJECT_DIR/esp-idf"
    GIT_STRATEGY: clone

  artifacts:
    paths:
      - build/*.bin
      - build/*.elf
      - build/*.map
      - build/bootloader/*.bin
      - build/partition_table/*.bin
      - build/customized_partitions/*.bin
      - build/flasher_args.json
      - build/download.config
      - build/factory/*
    expire_in: 6 mos

  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    # - git submodule update --init --recursive

  script:
    - cd main
    - rm -f at_config.h
    - echo -e "#ifndef __AT_CONFIG_H__" >> at_config.h
    - echo -e "#define __AT_CONFIG_H__" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_WROOM \"$AT_OTA_TOKEN_ESP32S2_WROOM\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_WROOM \"$AT_OTA_TOKEN_ESP32S2_WROOM\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_WROVER \"$AT_OTA_TOKEN_ESP32S2_WROVER\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_WROVER \"$AT_OTA_TOKEN_ESP32S2_WROVER\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_SOLO \"$AT_OTA_TOKEN_ESP32S2_SOLO\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_SOLO \"$AT_OTA_TOKEN_ESP32S2_SOLO\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_MINI \"$AT_OTA_TOKEN_ESP32S2_MINI\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_MINI \"$AT_OTA_TOKEN_ESP32S2_MINI\"" >> at_config.h
    - echo -e "#endif" >> at_config.h
    - cd -
    # replace submodule esp-idf to internal repository to speedup cloning
    - commit_str=$(awk '/commit:/{print $0}' module_config/module_esp32s2_default/IDF_VERSION)
    - branch_str=$(awk '/branch:/{print $0}' module_config/module_esp32s2_default/IDF_VERSION)
    - git clone -b ${branch_str#*branch:} ${GITLAB_SSH_SERVER}/idf/esp-idf.git
    - cd esp-idf
    - git checkout ${commit_str#*commit:}
    # (the same regular expressions are used to set these are used in 'only:' sections below
    - source ./tools/ci/configure_ci_environment.sh
    - tools/idf_tools.py install-python-env
    - tools/idf_tools.py install
    - source export.sh
    # fetch the submodules (& if necessary re-fetch repo) from gitlab
    - time ./tools/ci/get-full-sources.sh
    - git submodule update --init
    - cd -

    - export ESP_AT_PROJECT_PLATFORM=PLATFORM_ESP32S2
    - export ESP_AT_MODULE_NAME=SOLO
    - export ESP_AT_PROJECT_PATH=$(pwd)
    - pip install -r requirements.txt
    - ./esp-idf/tools/idf.py -DIDF_TARGET=esp32s2 build
    - cp build/flash_project_args build/download.config

esp32s2_mini_at:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp-env-v5.0:2
  tags:
    - build

  variables:
    IDF_PATH: "$CI_PROJECT_DIR/esp-idf"
    GIT_STRATEGY: clone

  artifacts:
    paths:
      - build/*.bin
      - build/*.elf
      - build/*.map
      - build/bootloader/*.bin
      - build/partition_table/*.bin
      - build/customized_partitions/*.bin
      - build/flasher_args.json
      - build/download.config
      - build/factory/*
    expire_in: 6 mos

  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    # - git submodule update --init --recursive

  script:
    - cd main
    - rm -f at_config.h
    - echo -e "#ifndef __AT_CONFIG_H__" >> at_config.h
    - echo -e "#define __AT_CONFIG_H__" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_WROOM \"$AT_OTA_TOKEN_ESP32S2_WROOM\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_WROOM \"$AT_OTA_TOKEN_ESP32S2_WROOM\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_WROVER \"$AT_OTA_TOKEN_ESP32S2_WROVER\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_WROVER \"$AT_OTA_TOKEN_ESP32S2_WROVER\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_SOLO \"$AT_OTA_TOKEN_ESP32S2_SOLO\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_SOLO \"$AT_OTA_TOKEN_ESP32S2_SOLO\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_MINI \"$AT_OTA_TOKEN_ESP32S2_MINI\"" >> at_config.h
    - echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_MINI \"$AT_OTA_TOKEN_ESP32S2_MINI\"" >> at_config.h
    - echo -e "#endif" >> at_config.h
    - cd -
    # replace submodule esp-idf to internal repository to speedup cloning
    - commit_str=$(awk '/commit:/{print $0}' module_config/module_esp32s2_default/IDF_VERSION)
    - branch_str=$(awk '/branch:/{print $0}' module_config/module_esp32s2_default/IDF_VERSION)
    - git clone -b ${branch_str#*branch:} ${GITLAB_SSH_SERVER}/idf/esp-idf.git
    - cd esp-idf
    - git checkout ${commit_str#*commit:}
    # (the same regular expressions are used to set these are used in 'only:' sections below
    - source ./tools/ci/configure_ci_environment.sh
    - tools/idf_tools.py install-python-env
    - tools/idf_tools.py install
    - source export.sh
    # fetch the submodules (& if necessary re-fetch repo) from gitlab
    - time ./tools/ci/get-full-sources.sh
    - git submodule update --init
    - cd -

    - export ESP_AT_PROJECT_PLATFORM=PLATFORM_ESP32S2
    - export ESP_AT_MODULE_NAME=MINI
    - export ESP_AT_PROJECT_PATH=$(pwd)
    - pip install -r requirements.txt
    - ./esp-idf/tools/idf.py -DIDF_TARGET=esp32s2 build
    - cp build/flash_project_args build/download.config

push_master_to_github:
  stage: deploy
  only:
    - master
    - /^release\/v.*$/
  tags:
    - deploy
  when: on_success
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  variables:
    GIT_STRATEGY: clone
    GITHUB_PUSH_REFS: refs/remotes/origin/release refs/remotes/origin/master
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GH_PUSH_KEY > ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git remote add github git@github.com:espressif/esp32-at.git
    # - git push --follow-tags github HEAD:master
    - eval $(git for-each-ref --shell bash --format 'if [ $CI_COMMIT_SHA == %(objectname) ]; then git checkout -B %(refname:strip=3); git push --follow-tags github %(refname:strip=3); fi;' $GITHUB_PUSH_REFS)

build_docs:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp-at-doc-env:1
  tags:
    - build_docs
  artifacts:
    when: always
    paths:
      # English version of documentation
      - docs/en/doxygen-warning-log.txt
      - docs/en/sphinx-warning-log.txt
      - docs/en/sphinx-warning-log-sanitized.txt
      - docs/en/_build/html
      - docs/sphinx-err-*
      # Chinese version of documentation
      - docs/zh_CN/doxygen-warning-log.txt
      - docs/zh_CN/sphinx-warning-log.txt
      - docs/zh_CN/sphinx-warning-log-sanitized.txt
      - docs/zh_CN/_build/html
    expire_in: 4 days
  only:
    variables:
      - $BOT_TRIGGER_WITH_LABEL == null
      - $BOT_LABEL_BUILD
      - $BOT_LABEL_BUILD_DOCS
      - $BOT_LABEL_REGULAR_TEST
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    # replace submodule esp-idf to internal repository to speedup cloning
    - commit_str=$(awk '/commit:/{print $0}' module_config/module_esp32_default/IDF_VERSION)
    - branch_str=$(awk '/branch:/{print $0}' module_config/module_esp32_default/IDF_VERSION)
    - git clone -b ${branch_str#*branch:} ${GITLAB_SSH_SERVER}/idf/esp-idf.git
    - cd esp-idf
    - git checkout ${commit_str#*commit:}
    # (the same regular expressions are used to set these are used in 'only:' sections below
    - source ./tools/ci/configure_ci_environment.sh
    - tools/idf_tools.py --non-interactive install && eval "$(tools/idf_tools.py --non-interactive export)" || exit 1
    # fetch the submodules (& if necessary re-fetch repo) from gitlab
    - time ./tools/ci/get-full-sources.sh
    - git submodule update --init
    - cd -

    - export IDF_PATH=$(pwd)/esp-idf
    - make defconfig
    # - ln -s $(IDF_PATH)/tools tools
    - cd docs
    - ./check_lang_folder_sync.sh
    - cd en
    # - make gh-linkcheck
    # skip to compile the documents due to deprecated python environment
    # - make html
    - ../check_doc_warnings.sh
    - cd ../zh_CN
    # - make gh-linkcheck
    # skip to compile the documents due to deprecated python environment
    # - make html
    - ../check_doc_warnings.sh
